FROM ruby:2.3.1

RUN adduser --disabled-password --gecos '' fractals

WORKDIR /home/fractals/app
COPY . .
RUN chown -R fractals:fractals .

USER fractals
# RUN bundle

CMD ["rails", "s", "-b", "0.0.0.0"]
