version: '2'
services:
  postgres:
    image: postgres:9.5.4
  redis:
    image: redis:3.2.3
  rails:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/home/fractals/app
    command: rails s -b 0.0.0.0
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/home/fractals/app
    command: sidekiq
  nginx:
    image: nginx:1.11.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
