FROM ruby:2.3.1

ENV RAILS_ENV production

RUN adduser --disabled-password --gecos '' fractals
WORKDIR /home/fractals/app

COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock
RUN bundle install --without development test

COPY . .
RUN chown -R fractals:fractals .

USER fractals

RUN ./bin/download-generate-fractal-binary

CMD ["unicorn", "-c", "./config/unicorn.rb"]
