base: &base
  adapter: postgresql
  host: postgres
  username: postgres

development:
  <<: *base
  database: fractals_dev

test:
  <<: *base
  database: fractals_test

production:
  <<: *base
  database: fractals_prod
